import type { PhotoCategory } from "@/lib/claude/ideaBookTypes";

// The one idea shown on the landing page's hero card. Not invented for the
// landing page: it is the first idea of the example Idea Book that the
// "Voorbeeld-Idea Book" links point at (public/examples/idea-book-*.pdf,
// generated by scripts/generate-example-idea-book.ts), copied verbatim. That
// script reuses the Dutch idea copy for the English PDF as well, so this card
// shows the same Dutch text in both site languages — it mirrors the PDF the
// visitor can open next to it. If the example book's first idea changes,
// update this too.
export const EXAMPLE_IDEA = {
  door: "natural",
  photoCategory: "creative_workshop" satisfies PhotoCategory,
  title: "Pottenbakken zoals je stiekem wilde",
  whyItFits: "Je zei zelf dat je best weer eens een workshop zou willen doen — hier is hij.",
  firstAction: "Zoek 'pottenbakken workshop' + je woonplaats en bekijk de eerstvolgende datum.",
} as const;
