// Photo paths of the discovery library. Kept apart from library.ts so client
// components can build an image URL without pulling the whole JSON library
// into the browser bundle.

/** Card photo of an activity. Generated by scripts/generate-discovery-illustrations.ts. */
export function activityImage(id: string): string {
  return `/illustrations/discovery/${id}.jpg`;
}

/** Photo of a domain card. */
export function domainImage(id: string): string {
  return `/illustrations/discovery/domains/${id}.jpg`;
}
